DROP TABLE IF EXISTS PDFDownloads.metadata;
CREATE TABLE PDFDownloads.metadata (
    BRnum varchar(255) key not null,
    AdherenceLevel varchar(255) null,
    ApplicationLevel varchar(255) null,
    AssuranceProvider varchar(255) null,
    AssuranceScope varchar(255) null,
    AssuranceStanadardISAE3000 boolean null,
    AssurancetandardAA1000AS boolean null,
    AssuranceStandardnationalGeneral boolean null,
    AssuranceStandardnationalSustainability boolean null,
    CDP boolean null,
    Country varchar(255) null,
    CountryStatus varchar(255) null,
    Databaselink varchar(255) null,
    DateAdded date null,
    ExternalAssurance boolean null,
    FeaturedReport boolean null,
    GOLDCommunity boolean null,
    GRIContentIndexURL varchar(255) null,
    GRIService varchar(255) null,
    IFC boolean null,
    ISO boolean null,
    PDFIntegrated boolean null,
    LevelOfAssurance varchar(255) null,
    Listed varchar(255) null,
    MaterialityMattersCheck boolean null,
    PDFName varchar(255) not null default '',
    OECD boolean null,
    OS boolean null,
    OrganizationType varchar(255) null,
    Pub_Year date null,
    Region varchar(255) not null default '',
    ReportDrtAddress varchar(255) null,
    ReportHtmlAddress varchar(255) null,
    Pdf_URL varchar(255) null,
    SDGs boolean null,
    Sector varchar(255) null,
    SectorSupplementsFinal varchar(255) null,
    PDFSize varchar(255) null,
    StakeholderPanel boolean null,
    PDFStatus varchar(255) null,
    Title varchar(255) null,
    PDFType varchar(255) null,
    TypeOfAssuranceProvider varchar(255) null,
    UNGC boolean null,
    DIHR_ID varchar(255) not null default '',
    pdf_downloaded varchar(255) null,
    English_dummy int null,
    English varchar(255) null
)